name: Deploy to DigitalOcean Droplet
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          username: ${{secrets.DROPLET_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd --
            cd ..
            cd ..
            cd var
            cd www
            cd digitaldevops.com.mx
            rm -rf demos_poc
            git clone git@github.com:DigitalDevopsMaster/demos_poc.git

            echo '------------------------------------'
            echo 'Deployment to DigitalOcean finished'
            echo '--'
